In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [35]:
import pandas as pd

df = pd.read_parquet("drive/MyDrive/green_tripdata_2026-01.parquet")

In [36]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,1,2026-01-01 00:27:58,2026-01-01 00:55:16,N,1.0,65,233,2.0,6.20,31.7,...,1.5,7.5,0.0,NaN,1.0,45.20,1.0,1.0,2.75,0.75
1,2,2026-01-01 00:44:33,2026-01-01 01:32:56,N,5.0,66,188,5.0,5.36,50.0,...,0.0,10.2,0.0,NaN,1.0,61.20,1.0,2.0,0.00,0.00
2,1,2026-01-01 00:23:45,2026-01-01 00:45:03,N,1.0,65,179,4.0,10.60,41.5,...,1.5,2.0,0.0,NaN,1.0,46.00,1.0,1.0,0.00,0.00
3,1,2026-01-01 00:44:33,2026-01-01 01:00:45,N,1.0,42,141,1.0,4.20,19.8,...,1.5,0.0,0.0,NaN,1.0,25.05,2.0,1.0,2.75,0.00
4,2,2026-01-01 00:46:04,2026-01-01 01:04:40,N,1.0,95,82,1.0,2.76,19.1,...,0.5,0.0,0.0,NaN,1.0,21.60,2.0,1.0,0.00,0.00

In [37]:
print(df.shape,df.size)

(40272, 21) 845712

In [38]:
df.isna().sum()

VendorID                     0
lpep_pickup_datetime         0
lpep_dropoff_datetime        0
store_and_fwd_flag        5414
RatecodeID                5414
PULocationID                 0
DOLocationID                 0
passenger_count           5414
trip_distance                0
fare_amount                  0
extra                        0
mta_tax                      0
tip_amount                   0
tolls_amount                 0
ehail_fee                40272
improvement_surcharge        0
total_amount                 0
payment_type              5414
trip_type                 5415
congestion_surcharge      5414
cbd_congestion_fee           0
dtype: int64

In [39]:
df['ehail_fee'].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: ehail_fee, dtype: float64

In [40]:
df = df.drop(columns=['ehail_fee','store_and_fwd_flag','VendorID','payment_type'] , axis=1)

In [41]:
df.isna().sum()

lpep_pickup_datetime        0
lpep_dropoff_datetime       0
RatecodeID               5414
PULocationID                0
DOLocationID                0
passenger_count          5414
trip_distance               0
fare_amount                 0
extra                       0
mta_tax                     0
tip_amount                  0
tolls_amount                0
improvement_surcharge       0
total_amount                0
trip_type                5415
congestion_surcharge     5414
cbd_congestion_fee          0
dtype: int64

In [42]:
drop_cols = [
    "total_amount",
    "tip_amount",
    "tolls_amount",
    "fare_amount",
]

df = df.drop(columns=drop_cols)

In [43]:
df.isna().sum()

lpep_pickup_datetime        0
lpep_dropoff_datetime       0
RatecodeID               5414
PULocationID                0
DOLocationID                0
passenger_count          5414
trip_distance               0
extra                       0
mta_tax                     0
improvement_surcharge       0
trip_type                5415
congestion_surcharge     5414
cbd_congestion_fee          0
dtype: int64

In [44]:
df["trip_duration"] = (
    df["lpep_dropoff_datetime"]
    - df["lpep_pickup_datetime"]
).dt.total_seconds()

In [45]:
df = df.drop(columns=["lpep_dropoff_datetime"])

In [46]:
df["pickup_hour"] = df["lpep_pickup_datetime"].dt.hour
df["pickup_day"] = df["lpep_pickup_datetime"].dt.dayofweek
df["pickup_month"] = df["lpep_pickup_datetime"].dt.month

In [25]:
df.isna().sum()

lpep_pickup_datetime        0
RatecodeID               5414
PULocationID                0
DOLocationID                0
passenger_count          5414
trip_distance               0
extra                       0
mta_tax                     0
improvement_surcharge       0
trip_type                5415
congestion_surcharge     5414
cbd_congestion_fee          0
trip_duration               0
pickup_hour                 0
pickup_day                  0
pickup_month                0
dtype: int64

## **Fill The Missing**

In [47]:
df["RatecodeID"] = df["RatecodeID"].fillna(-1)
df["passenger_count"] = df["passenger_count"].fillna(
    df["passenger_count"].median()
)
df["trip_type"] = df["trip_type"].fillna(-1)
df["trip_type"] = df["trip_type"].fillna("Unknown")
df["congestion_surcharge"] = df["congestion_surcharge"].fillna(0)

In [30]:
df.isna().sum()

lpep_pickup_datetime     0
RatecodeID               0
PULocationID             0
DOLocationID             0
passenger_count          0
trip_distance            0
extra                    0
mta_tax                  0
improvement_surcharge    0
trip_type                0
congestion_surcharge     0
cbd_congestion_fee       0
trip_duration            0
pickup_hour              0
pickup_day               0
pickup_month             0
dtype: int64

In [48]:
df.head()

,lpep_pickup_datetime,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,extra,mta_tax,improvement_surcharge,trip_type,congestion_surcharge,cbd_congestion_fee,trip_duration,pickup_hour,pickup_day,pickup_month
0,2026-01-01 00:27:58,1.0,65,233,2.0,6.20,4.50,1.5,1.0,1.0,2.75,0.75,1638.0,0,3,1
1,2026-01-01 00:44:33,5.0,66,188,5.0,5.36,0.00,0.0,1.0,2.0,0.00,0.00,2903.0,0,3,1
2,2026-01-01 00:23:45,1.0,65,179,4.0,10.60,1.00,1.5,1.0,1.0,0.00,0.00,1278.0,0,3,1
3,2026-01-01 00:44:33,1.0,42,141,1.0,4.20,3.75,1.5,1.0,1.0,2.75,0.00,972.0,0,3,1
4,2026-01-01 00:46:04,1.0,95,82,1.0,2.76,1.00,0.5,1.0,1.0,0.00,0.00,1116.0,0,3,1

In [49]:
df.drop(columns= 'lpep_pickup_datetime',inplace=True)

In [50]:
df.head()

,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,extra,mta_tax,improvement_surcharge,trip_type,congestion_surcharge,cbd_congestion_fee,trip_duration,pickup_hour,pickup_day,pickup_month
0,1.0,65,233,2.0,6.20,4.50,1.5,1.0,1.0,2.75,0.75,1638.0,0,3,1
1,5.0,66,188,5.0,5.36,0.00,0.0,1.0,2.0,0.00,0.00,2903.0,0,3,1
2,1.0,65,179,4.0,10.60,1.00,1.5,1.0,1.0,0.00,0.00,1278.0,0,3,1
3,1.0,42,141,1.0,4.20,3.75,1.5,1.0,1.0,2.75,0.00,972.0,0,3,1
4,1.0,95,82,1.0,2.76,1.00,0.5,1.0,1.0,0.00,0.00,1116.0,0,3,1

In [51]:
df['PU_DO'] = df['PULocationID'].astype(str) + '_' + df['DOLocationID'].astype(str)

In [52]:
df.head()

,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,extra,mta_tax,improvement_surcharge,trip_type,congestion_surcharge,cbd_congestion_fee,trip_duration,pickup_hour,pickup_day,pickup_month,PU_DO
0,1.0,65,233,2.0,6.20,4.50,1.5,1.0,1.0,2.75,0.75,1638.0,0,3,1,65_233
1,5.0,66,188,5.0,5.36,0.00,0.0,1.0,2.0,0.00,0.00,2903.0,0,3,1,66_188
2,1.0,65,179,4.0,10.60,1.00,1.5,1.0,1.0,0.00,0.00,1278.0,0,3,1,65_179
3,1.0,42,141,1.0,4.20,3.75,1.5,1.0,1.0,2.75,0.00,972.0,0,3,1,42_141
4,1.0,95,82,1.0,2.76,1.00,0.5,1.0,1.0,0.00,0.00,1116.0,0,3,1,95_82

In [53]:
df.drop(columns=['PULocationID','DOLocationID'],inplace=True)

In [55]:
df.columns

Index(['RatecodeID', 'passenger_count', 'trip_distance', 'extra', 'mta_tax',
       'improvement_surcharge', 'trip_type', 'congestion_surcharge',
       'cbd_congestion_fee', 'trip_duration', 'pickup_hour', 'pickup_day',
       'pickup_month', 'PU_DO'],
      dtype='object')